alias ls='ls --color=auto'
alias upgrade='sudo yaourt --aur -Syyu'
alias pacman='sudo pacman'
alias ll='ls -al'
alias fmenu='fluxbox-generate_menu'
alias cpdir='cp -rv'
alias terabyte='cd /media/Terabyte'
alias windoze='cd /media/Windoze'
alias opmenu='mmaker -vf OpenBox3 && openbox --reconfigure'
alias vi='vim'
alias vbox='sudo modprobe vboxdrv && sudo modprobe vboxnetflt && sudo modprobe vboxnetadp'
alias rmdir='rm -rv'
alias unamedate='echo "Issuing uname -a:" && uname -a && echo "Current Date and Time:" && date'
alias ASS='sudo shutdown -hP 1 "ASS - Awesome Shutdown Sequence"'
alias ASSQ='sudo shutdown -hP now "ASS - Awesome Shutdown Sequence"'
alias ASSN='sudo shutdown -hP'
alias ARSE='sudo shutdown -r 1 "ARSE - Awesome Reboot Sequence... Executed."'
alias ARSEQ='sudo shutdown -r now "ARSE - Awesome Reboot Sequence... Executed."'
alias photoshop='env WINEPREFIX="/home/burchettm/.wineprefix/Adobe" wine "/home/burchettm/.wineprefix/Adobe/drive_c/Program Files/Adobe/Photoshop 7.0/Photoshop.exe"'
