[Desktop Entry]
Name=Crux Blue
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=Crux
MetacityTheme=Crux
IconTheme=gnome
GtkColorScheme=fg_color:#101010101010,bg_color:#e8c7eaeaebeb,text_color:#1a1a1a1a1a1a,base_color:#ffffffffffff,selected_fg_color:#ffffffffffff,selected_bg_color:#44586c809421,tooltip_fg_color:#ffffffffffff,tooltip_bg_color:#56b556b556b5
CursorTheme=default
CursorSize=18
