[Desktop Entry]
Name=Crux White
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=Crux
MetacityTheme=Crux
IconTheme=gnome
GtkColorScheme=fg_color:#101010101010,bg_color:#d9f4db73dc28,text_color:#1a1a1a1a1a1a,base_color:#ee14ee14ee14,selected_fg_color:#000000000000,selected_bg_color:#ffffffffffff,tooltip_fg_color:#ffffffffffff,tooltip_bg_color:#56b556b556b5
CursorTheme=default
CursorSize=18
