#!/bin/sh

SERVICE=synergys

if [ -n 'pgrep synergys >/dev/null' ]
then
echo "$SERVICE is NOT running."
#echo "Starting $SERVICE ..."
#synergys -c /home/burchettm/.quicksynergy/synergy.conf
#  if pgrep $SERVICE > /dev/null
#  then
#  echo "$SERVICE started ..."
#  else
#  echo "$SERVICE failed to start ..."
#  fi
else
echo "$SERVICE is running."
fi
