#!/bin/zsh

SERVICE=x11vnc

if pidof $SERVICE > /dev/null
then
echo "$SERVICE is running."
#echo "Starting $SERVICE ..."
#synergys -c /home/burchettm/.quicksynergy/synergy.conf
#  if pgrep $SERVICE > /dev/null
#  then
#  echo "$SERVICE started ..."
#  else
#  echo "$SERVICE failed to start ..."
#  fi
else

echo "$SERVICE is NOT running."
echo "Starting $SERVICE ..."

x11vnc -rfbauth -bg -q ~/.vnc/passwd >> /home/burchettm/.log/x11vnc.log
  if pidof $SERVICE > /dev/null
  then
  echo "$SERVICE started ..."
  else
  echo "$SERVICE failed to start ..."
  fi

fi
